package model;
// Generated 23/05/2017 10:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GrupoUsuario generated by hbm2java
 */
public class GrupoUsuario  implements java.io.Serializable {


     private int idGrupo;
     private String nombreGrupo;
     private Set usuarios = new HashSet(0);

    public GrupoUsuario() {
    }

	
    public GrupoUsuario(int idGrupo, String nombreGrupo) {
        this.idGrupo = idGrupo;
        this.nombreGrupo = nombreGrupo;
    }
    public GrupoUsuario(int idGrupo, String nombreGrupo, Set usuarios) {
       this.idGrupo = idGrupo;
       this.nombreGrupo = nombreGrupo;
       this.usuarios = usuarios;
    }
   
    public int getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(int idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


