package model;
// Generated 23/05/2017 10:07:46 by Hibernate Tools 4.3.1



/**
 * MascotaVacunaId generated by hbm2java
 */
public class MascotaVacunaId  implements java.io.Serializable {


     private int idMascota;
     private int idVacuna;

    public MascotaVacunaId() {
    }

    public MascotaVacunaId(int idMascota, int idVacuna) {
       this.idMascota = idMascota;
       this.idVacuna = idVacuna;
    }
   
    public int getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(int idMascota) {
        this.idMascota = idMascota;
    }
    public int getIdVacuna() {
        return this.idVacuna;
    }
    
    public void setIdVacuna(int idVacuna) {
        this.idVacuna = idVacuna;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MascotaVacunaId) ) return false;
		 MascotaVacunaId castOther = ( MascotaVacunaId ) other; 
         
		 return (this.getIdMascota()==castOther.getIdMascota())
 && (this.getIdVacuna()==castOther.getIdVacuna());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMascota();
         result = 37 * result + this.getIdVacuna();
         return result;
   }   


}


