package model;
// Generated 23/05/2017 10:07:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MascotaVacuna generated by hbm2java
 */
public class MascotaVacuna  implements java.io.Serializable {


     private MascotaVacunaId id;
     private Mascota mascota;
     private MedicoVeterinario medicoVeterinario;
     private Vacuna vacuna;
     private String nombreVacuna;
     private String detallesDosis;
     private Date fechaAplicacion;

    public MascotaVacuna() {
    }

    public MascotaVacuna(MascotaVacunaId id, Mascota mascota, MedicoVeterinario medicoVeterinario, Vacuna vacuna, String nombreVacuna, String detallesDosis, Date fechaAplicacion) {
       this.id = id;
       this.mascota = mascota;
       this.medicoVeterinario = medicoVeterinario;
       this.vacuna = vacuna;
       this.nombreVacuna = nombreVacuna;
       this.detallesDosis = detallesDosis;
       this.fechaAplicacion = fechaAplicacion;
    }
   
    public MascotaVacunaId getId() {
        return this.id;
    }
    
    public void setId(MascotaVacunaId id) {
        this.id = id;
    }
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    public MedicoVeterinario getMedicoVeterinario() {
        return this.medicoVeterinario;
    }
    
    public void setMedicoVeterinario(MedicoVeterinario medicoVeterinario) {
        this.medicoVeterinario = medicoVeterinario;
    }
    public Vacuna getVacuna() {
        return this.vacuna;
    }
    
    public void setVacuna(Vacuna vacuna) {
        this.vacuna = vacuna;
    }
    public String getNombreVacuna() {
        return this.nombreVacuna;
    }
    
    public void setNombreVacuna(String nombreVacuna) {
        this.nombreVacuna = nombreVacuna;
    }
    public String getDetallesDosis() {
        return this.detallesDosis;
    }
    
    public void setDetallesDosis(String detallesDosis) {
        this.detallesDosis = detallesDosis;
    }
    public Date getFechaAplicacion() {
        return this.fechaAplicacion;
    }
    
    public void setFechaAplicacion(Date fechaAplicacion) {
        this.fechaAplicacion = fechaAplicacion;
    }




}


