package model;
// Generated 23/05/2017 10:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MedicoVeterinario generated by hbm2java
 */
public class MedicoVeterinario  implements java.io.Serializable {


     private int idMedico;
     private String nombre;
     private String apellido;
     private int nroRegistro;
     private Set mascotaVacunas = new HashSet(0);

    public MedicoVeterinario() {
    }

	
    public MedicoVeterinario(int idMedico, String nombre, String apellido, int nroRegistro) {
        this.idMedico = idMedico;
        this.nombre = nombre;
        this.apellido = apellido;
        this.nroRegistro = nroRegistro;
    }
    public MedicoVeterinario(int idMedico, String nombre, String apellido, int nroRegistro, Set mascotaVacunas) {
       this.idMedico = idMedico;
       this.nombre = nombre;
       this.apellido = apellido;
       this.nroRegistro = nroRegistro;
       this.mascotaVacunas = mascotaVacunas;
    }
   
    public int getIdMedico() {
        return this.idMedico;
    }
    
    public void setIdMedico(int idMedico) {
        this.idMedico = idMedico;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public int getNroRegistro() {
        return this.nroRegistro;
    }
    
    public void setNroRegistro(int nroRegistro) {
        this.nroRegistro = nroRegistro;
    }
    public Set getMascotaVacunas() {
        return this.mascotaVacunas;
    }
    
    public void setMascotaVacunas(Set mascotaVacunas) {
        this.mascotaVacunas = mascotaVacunas;
    }




}


