package model;
// Generated 23/05/2017 10:07:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProxVacuna generated by hbm2java
 */
public class ProxVacuna  implements java.io.Serializable {


     private int idProxVacuna;
     private Mascota mascota;
     private Date fechaProxVacuna;
     private String nombreVacuna;
     private String detalles;

    public ProxVacuna() {
    }

	
    public ProxVacuna(int idProxVacuna, Mascota mascota, Date fechaProxVacuna, String nombreVacuna) {
        this.idProxVacuna = idProxVacuna;
        this.mascota = mascota;
        this.fechaProxVacuna = fechaProxVacuna;
        this.nombreVacuna = nombreVacuna;
    }
    public ProxVacuna(int idProxVacuna, Mascota mascota, Date fechaProxVacuna, String nombreVacuna, String detalles) {
       this.idProxVacuna = idProxVacuna;
       this.mascota = mascota;
       this.fechaProxVacuna = fechaProxVacuna;
       this.nombreVacuna = nombreVacuna;
       this.detalles = detalles;
    }
   
    public int getIdProxVacuna() {
        return this.idProxVacuna;
    }
    
    public void setIdProxVacuna(int idProxVacuna) {
        this.idProxVacuna = idProxVacuna;
    }
    public Mascota getMascota() {
        return this.mascota;
    }
    
    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    public Date getFechaProxVacuna() {
        return this.fechaProxVacuna;
    }
    
    public void setFechaProxVacuna(Date fechaProxVacuna) {
        this.fechaProxVacuna = fechaProxVacuna;
    }
    public String getNombreVacuna() {
        return this.nombreVacuna;
    }
    
    public void setNombreVacuna(String nombreVacuna) {
        this.nombreVacuna = nombreVacuna;
    }
    public String getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(String detalles) {
        this.detalles = detalles;
    }




}


