package model;
// Generated 23/05/2017 10:07:46 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private GrupoUsuario grupoUsuario;
     private String usuario;
     private String nombre;
     private String apellido;
     private String password;

    public Usuario() {
    }

    public Usuario(int idUsuario, GrupoUsuario grupoUsuario, String usuario, String nombre, String apellido, String password) {
       this.idUsuario = idUsuario;
       this.grupoUsuario = grupoUsuario;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.password = password;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public GrupoUsuario getGrupoUsuario() {
        return this.grupoUsuario;
    }
    
    public void setGrupoUsuario(GrupoUsuario grupoUsuario) {
        this.grupoUsuario = grupoUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


