package model;
// Generated 23/05/2017 10:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vacuna generated by hbm2java
 */
public class Vacuna  implements java.io.Serializable {


     private int idVacuna;
     private String nombreVacuna;
     private String descripcion;
     private Set mascotaVacunas = new HashSet(0);

    public Vacuna() {
    }

	
    public Vacuna(int idVacuna, String nombreVacuna, String descripcion) {
        this.idVacuna = idVacuna;
        this.nombreVacuna = nombreVacuna;
        this.descripcion = descripcion;
    }
    public Vacuna(int idVacuna, String nombreVacuna, String descripcion, Set mascotaVacunas) {
       this.idVacuna = idVacuna;
       this.nombreVacuna = nombreVacuna;
       this.descripcion = descripcion;
       this.mascotaVacunas = mascotaVacunas;
    }
   
    public int getIdVacuna() {
        return this.idVacuna;
    }
    
    public void setIdVacuna(int idVacuna) {
        this.idVacuna = idVacuna;
    }
    public String getNombreVacuna() {
        return this.nombreVacuna;
    }
    
    public void setNombreVacuna(String nombreVacuna) {
        this.nombreVacuna = nombreVacuna;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getMascotaVacunas() {
        return this.mascotaVacunas;
    }
    
    public void setMascotaVacunas(Set mascotaVacunas) {
        this.mascotaVacunas = mascotaVacunas;
    }




}


